### ISSUE TITLE
JSON-LD

### ISSUE THREAD

**Issue by akuckartz** [martinblech/mimerender#26]
`application/ld+json`should be added.

**Comment by martinblech** [comment]
Thank you for your input, @akuckartz !
You can already use it by calling [`register_mime('jsonld', ('application/ld+json',))`](https://github.com/martinblech/mimerender/blob/master/src/mimerender.py#L57). If you would like to include it in the list of built-in media types, please submit a pull request. It's only a matter of adding it to the [`_MIME_TYPES`](https://github.com/martinblech/mimerender/blob/master/src/mimerender.py#L35) dictionary.

**Comment by martinblech** [comment]
fixed in v0.5.5
