### ISSUE TITLE
Include copy of license in source / tarballs

### ISSUE THREAD

**Issue by AdamWill** [martinblech/mimerender#29]
mimerender claims MIT as its license, but AFAICT does not include the text of the license anywhere in the source tree on github, nor in the release tarballs. The MIT license includes this text:

" The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

i.e. the license itself requires that it be included with distributions of the code, yet the canonical distribution of the code does not include it. As the Fedora licensing guidelines - https://fedoraproject.org/wiki/Packaging:LicensingGuidelines - and similar guidelines for other distributions (e.g. Debian) state, "In cases where the upstream has chosen a license that requires that a copy of the license text be distributed along with the binaries and/or source code, but does not provide a copy of the license text (in the source tree, or in some rare cases, anywhere), the packager should do their best to point out this confusion to upstream.", so I am doing that. Please include a copy of the license in the source. The usual way to do this would be to include the text in the top-level directory as a file named `LICENSE` or `COPYING`.

**Comment by martinblech** [comment]
LGTM, thanks!

**Comment by AdamWill** [comment]
Note the file still doesn't show up in the *tarballs*, as reported in https://github.com/martinblech/mimerender/issues/34 :(
