### ISSUE TITLE
Content-Type sometimes wrong with recent Python 3 and pypy(?)

### ISSUE THREAD

**Issue by AdamWill** [martinblech/mimerender#31]
You have a few travis runs - one for the most recent commit:

https://travis-ci.org/martinblech/mimerender/builds/55794367

and two for recent PRs:

https://travis-ci.org/martinblech/mimerender/builds/55276527
https://travis-ci.org/martinblech/mimerender/builds/103693109

where the 'pypy' run of the test suite failed, with two tests failing because of Content-Type being 'application/xml' instead of 'text/xml'. Interestingly, I seem to get the exact same error sometimes when running the test suite with Python 3 on Fedora Rawhide - that's Python 3.5. It never seems to fail with Python 2. *Sometimes* the test suite passes, though.

I'm afraid I don't know what the actual problem is, but clearly there's some kind of issue there.

**Comment by martinblech** [comment]
Seems this was fixed with #33. Thanks for reporting this!
